application: battleshipchallenge
module: default
version: 1
runtime: python27
instance_class: F1
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /(.*)
  static_files: app/\1
  upload: app/(.*)
